name: basic_flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/dog_image1.jpg
    - assets/dog_image2.jpg
    - assets/dog_image3.jpg

  fonts: 
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100




